Custom errors new option
rnsdomains/rns-js pull request #41
Opened 2020-03-04 21:18 UTC by javiesses

2020-03-04 21:19 UTC, javiesses commented
Closes #32

2020-03-05 16:19 UTC, ilanolkies requested changes
Great job!

2020-03-05 16:19 UTC, ilanolkies commented on test/utils.ts
> +    expect(error.id).toBe(expectedErrorId);
```suggestion
    expect(error).toEqual(new RNSError(expectedError));
```

??

2020-03-05 16:19 UTC, ilanolkies commented on package.json
> +    "lint": "npx eslint 'src/**.ts' 'src/**/**.ts' 'test/**'",
```suggestion
    "lint": "npx run lint:src && npx run lint:test",
    "lint:src": "npx eslint ./src",
    "lint:test": "npx eslint ./test",
```

2020-03-05 16:37 UTC, ilanolkies commented on package.json
> +    "lint": "npx eslint 'src/**.ts' 'src/**/**.ts' 'test/**'",
Paths in eslint are strange...

2020-03-05 16:38 UTC, ilanolkies approved these changes

2020-03-05 16:40 UTC, merged